### ISSUE TITLE
app template files are not shipped with 0.6.0 pypi dist

### ISSUE THREAD

**Issue by keighrim** [clamsproject/clams-python#132]
### Bug Description

When I tried to create a new app with `clams develop` command,  it didn't work because templates were not properly packed into the 0.6.0 pypi distribution, and hence raises `FileNotFoundError`s. 

### Reproduction steps

``` bash 
$ clams --version
0.6.0 (based on MMIF spec: 0.5.0)
$ clams develop -n newapp
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/new/bin/clams", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/new/lib/python3.8/site-packages/clams/__init__.py", line 44, in cli
    develop.main(args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/new/lib/python3.8/site-packages/clams/develop/__init__.py", line 97, in main
    cutter.bake()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/new/lib/python3.8/site-packages/clams/develop/__init__.py", line 52, in bake
    shutil.copytree(src_dir, dst_dir)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/new/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/Caskroom/miniconda/base/envs/new/lib/python3.8/site-packages/clams/develop/templates/github'
$ 
```

**Comment by keighrim** [comment]
fixed via #133
